{
    'name': 'Office Supplies',
    'version': '1.0.0',
    'author': 'abc',
    'category': 'Tools',
    'sequence' : -101,
    'summary': 'Office supplies for office use',
    'description': """list of items used in office""",
    'depends' : [],
    'data' : [
        'security/ir.model.access.csv',
        'wizard/message_wizard_view.xml',
        'views/items_view.xml',
        'views/menu.xml',
    ],
    'demo' : [],
    'installable':True,
    'auto_install':False,
    'application': True,
    'Liscense':'LGPL-3',
}